### ISSUE TITLE
NULL Prim Path Error

### ISSUE THREAD

**Issue by Huster-YZY** [SamuelSchmidgall/SurgicalGym#1]
Great job! I've encountered some difficulties while running SurgicalGym and I was hoping you could provide some assistance.

The error message I'm receiving is: 'pxrInternal_v0_22__pxrReserved__::UsdPrim::_ApplyAPI' at line 450 in file /buildAgent/work/ac88d7d902b57417/USD/pxr/usd/usd/prim.cpp : 'Invalid prim 'null prim' ".

Upon reviewing the code, I suspect that the issue might be related to the 'prim_path' in the 'star.py' file at line 100 and the 'psm.py' file at line 98. I noticed that the value of 'self.default_zero_env_path' is set to '/World/envs/env_0', which doesn't exist on my computer.

Could you please suggest a solution to resolve this problem?

Thank you for your attention and assistance.

**Comment by SamuelSchmidgall** [comment]
Sorry for the delay, are you still having this issue? I wonder if you need to regenerate the USD on your local machine.
