### ISSUE TITLE
Problems with LapGym

### ISSUE THREAD

**Issue by AndreaCusinato** [SamuelSchmidgall/SurgicalGym#3]
Good evening, 
I'm Andrea, a student of the Bachelor's Degree in Biomedical Engineering at the University of Genoa. Reading the paper "Surgical Gym: A high-performance GPU-based platform for reinforcement learning with surgical robots" I saw that you mentioned LapGym by Scheikl. 
I'm trying to use sofa_env, which is inside LapGym, but I have a problem executing the test code. Have you used this SOFA plugin? I use Windows. 
Best regards, Andrea

**Comment by SamuelSchmidgall** [comment]
This repo is not related to LapGym or SOFA.
